apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ include "chart.fullname" . }}-app"
  labels:
{{ toYaml .Values.app.labels | indent 4 }}
spec:
  replicas: {{ .Values.app.autoscaling.desiredReplicaCount }}
  strategy:
{{ toYaml .Values.app.updateStrategy | indent 4 }}
  selector:
    matchLabels:
{{ toYaml .Values.app.labels | indent 6 }}
  template:
    metadata:
      annotations:
{{ toYaml .Values.app.podAnnotations | indent 8 }}
      labels:
{{ toYaml .Values.app.labels | indent 8 }}
    spec:
      topologySpreadConstraints:
      - maxSkew: 1
        topologyKey: topology.kubernetes.io/zone
        whenUnsatisfiable: ScheduleAnyway
        labelSelector:
          matchLabels:
{{ toYaml .Values.app.labels | indent 12 }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.app.image.repository }}:{{ .Values.app.image.tag }}"
          imagePullPolicy: {{ .Values.app.image.pullPolicy }}
          env:
{{- if .Values.app.env }}
{{ toYaml .Values.app.env | indent 12 }}
{{- end }}
          ports:
            - name: app
              containerPort: {{ .Values.app.container.port }}
              protocol: {{ .Values.app.container.protocol }}
          readinessProbe:
{{ toYaml .Values.app.readinessProbe | indent 12 }}
          livenessProbe:
{{ toYaml .Values.app.livenessProbe | indent 12 }}
          resources:
            {{- toYaml .Values.app.resources | nindent 12 }}
      {{- with .Values.app.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.app.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.app.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}