apiVersion: v1
kind: Service
metadata:
  name: "{{ include "chart.fullname" . }}-app"
  annotations:
{{ toYaml .Values.app.service.annotations | indent 4 }}
  labels:
{{ toYaml .Values.app.labels | indent 4 }}
spec:
  type: {{ .Values.app.service.type }}
  ports:
    - port: {{ .Values.app.service.port }}
      targetPort: {{ .Values.app.service.targetPort }}
      protocol: {{ .Values.app.service.protocol }}
      name: http
  selector:
{{ toYaml .Values.app.labels | indent 4 }}