{{- if .Values.app.autoscaling.enabled }}
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: "{{ include "chart.fullname" . }}-app"
spec:
  scaleTargetRef:
    apiVersion: apps/v1beta1
    kind: Deployment
    name: "{{ include "chart.fullname" . }}-app"
  minReplicas: {{ toYaml .Values.app.autoscaling.minReplicas }}
  maxReplicas: {{ toYaml .Values.app.autoscaling.maxReplicas }}
  targetCPUUtilizationPercentage: {{ toYaml .Values.app.autoscaling.targetCPUUtilizationPercentage }}
{{- end }}