apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: "{{ include "chart.fullname" . }}-fapp"
  annotations:
{{ toYaml .Values.fapp.ingress.annotations | indent 4 }}
  labels:
{{ toYaml .Values.fapp.labels | indent 4 }}
spec:
  {{- if .Values.fapp.ingress.ingressClassName }}
  ingressClassName: {{ .Values.fapp.ingress.ingressClassName }}
  {{- end }}
  defaultBackend:
    service:
      name: "{{ include "chart.fullname" . }}-fapp"
      port:
        number: {{ .Values.fapp.service.port }}
  rules:
    - host: {{ .Values.fapp.ingress.host }}
      http:
        paths:
          - path: {{ .Values.fapp.ingress.path }}
            pathType: Prefix
            backend:
              service:
                name: "{{ include "chart.fullname" . }}-fapp"
                port:
                  number: {{ .Values.fapp.service.port }}