export const dataForYahooSearchEngine = {
  id: '09211703-7049-0121-0000-37cc6ddb0c16',
  status_code: 20000,
  status_message: 'Ok.',
  time: '12.0430 sec.',
  cost: 0.002,
  result_count: 1,
  path: ['v3', 'serp', 'yahoo', 'organic', 'live', 'regular'],
  data: {
    api: 'serp',
    function: 'live',
    se: 'yahoo',
    se_type: 'organic',
    keyword: 'iphone',
    location_code: 2826,
    language_code: 'en',
    device: 'desktop',
    os: 'windows',
    depth: 100,
  },
  result: [
    {
      keyword: 'iphone',
      type: 'organic',
      se_domain: 'uk.search.yahoo.com',
      location_code: 2826,
      language_code: 'en',
      check_url:
        'https://uk.search.yahoo.com/search?p=iphone&vl=lang_en&vc=gb&fr=sfp&lat=55.378051&lon=-3.435973&locupdate=1&radius=150&fr2=p%3As%2Cv%3Aw%2Cm%3Aloc',
      datetime: '2024-09-21 14:04:06 +00:00',
      spell: null,
      item_types: [
        'top_stories',
        'organic',
        'video',
        'people_also_ask',
        'related_searches',
        'paid',
      ],
      se_results_count: 19400000,
      items_count: 47,
      items: [
        {
          type: 'organic',
          rank_group: 1,
          rank_absolute: 2,
          domain: 'www.apple.com',
          title: 'iPhone - Apple (UK)',
          description:
            'iPhone and Mac. With iPhone Mirroring, you can view your iPhone screen on your Mac and control it without picking up your phone. Continuity features also let you answer calls or messages on your Mac. You can even copy images, video or text from your iPhone and paste it all into a different app on your Mac. And with iCloud, you can access your ...',
          url: 'https://www.apple.com/uk/iphone/',
          breadcrumb: 'www.apple.com › uk › iphone',
        },
        {
          type: 'organic',
          rank_group: 2,
          rank_absolute: 3,
          domain: 'www.apple.com',
          title: 'Buy iPhone - Apple (UK)',
          description:
            'Apple Fitness+ requires iPhone 8 or later with iOS 16.1 or later or Apple Watch Series 3 or later with watchOS 7.2 or later paired with iPhone 6s or later with iOS 14.3 or later. 2. Apple reports data about the recycled content of its products at different levels of fidelity, based on the level of independent data verification.',
          url: 'https://www.apple.com/uk/shop/buy-iphone',
          breadcrumb: 'www.apple.com › uk › shop',
        },
        {
          type: 'organic',
          rank_group: 3,
          rank_absolute: 4,
          domain: 'www.apple.com',
          title: 'iPhone - Apple',
          description:
            'Price for iPhone 16 and iPhone 16 Plus includes $30 AT&T connectivity discount. Activation required. Boost Mobile iPhone 16 Special Deal: Buy an iPhone 16 Pro, iPhone 16 Pro Max, iPhone 16, or iPhone 16 Plus and get $1000 in bill credits (not to exceed the cost of the iPhone ) applied over 36 months.',
          url: 'https://www.apple.com/iphone/',
          breadcrumb: 'www.apple.com › iphone',
        },
        {
          type: 'organic',
          rank_group: 4,
          rank_absolute: 6,
          domain: 'www.argos.co.uk',
          title: 'Apple iPhone - Argos',
          description:
            'iPhone 13 and iPhone 13 mini. Advanced dual-camera system. Lightning-fast A15 Bionic chip. A big leap in battery life. Durable design. Superfast 5G.1 And brighter 6.1-inch and 5.4-inch Super Retina XDR displays.². iPhone 13: 6.1-inch Super Retina XDR display.². A15 Bionic chip with 4-core GPU.',
          url: 'https://www.argos.co.uk/brands/apple-iphone',
          breadcrumb: 'www.argos.co.uk › brands › apple-iphone',
        },
        {
          type: 'organic',
          rank_group: 5,
          rank_absolute: 7,
          domain: 'www.johnlewis.com',
          title: 'Apple iPhones - John Lewis & Partners',
          description:
            'Apple iPhone 16, iOS, 6.1", 5G, SIM Free, 256GB. £899.00. Save 20% on the Apple 20W USB-C Power Adapter (2024) when bought with this item (via promo code, see product page for details) View offers. Pre-order now for delivery from 20 September 2024. Add to basket.',
          url: 'https://www.johnlewis.com/browse/electricals/mobile-phones-accessories/view-all-mobile-phones/apple/_/N-a8vZ1z13zz4',
          breadcrumb: 'www.johnlewis.com › browse › electricals',
        },
        {
          type: 'organic',
          rank_group: 6,
          rank_absolute: 8,
          domain: 'support.apple.com',
          title: 'iPhone - Official Apple Support',
          description:
            'iPhone User Guide. Learn about all the features, apps, and settings of your iPhone. Accidents happen. AppleCare+ covers them. Get unlimited repairs for accidental damage protection, 24/7 priority access to Apple experts, and more. You also have the option to get theft and loss coverage.',
          url: 'https://support.apple.com/iphone',
          breadcrumb: 'support.apple.com › iphone',
        },
        {
          type: 'organic',
          rank_group: 7,
          rank_absolute: 9,
          domain: 'www.currys.co.uk',
          title: 'Buy APPLE iPhone 12 - 64 GB, Black - Currys',
          description:
            "Product information. Product code: 313538. Apple iPhone 12 is packed with smart and powerful features. The A14 Bionic chip and its 16-core Neural Engine are running the show and they don't get slowed down by any app or game. From Apple TV to emails, everything looks amazing on the 6.1” Super Retina XDR display.",
          url: 'https://www.currys.co.uk/products/apple-iphone-12-64-gb-black-10215596.html',
          breadcrumb: 'www.currys.co.uk › products › apple-iphone-12-64-gb',
        },
        {
          type: 'paid',
          rank_group: 1,
          rank_absolute: 12,
          domain: 'www.o2.co.uk',
          title: 'AdFree Next Day Delivery - Shop iPhone 16 For £36.53/m',
          description:
            'Save Up To £600 With Trade-In. Order The iPhone 16 For £36.53/m On O2. New Release. Order The Apple iPhone 16 128GB & Save Up To £600 With Trade-In',
          url: 'https://www.o2.co.uk/shop/apple/iphone-16',
          breadcrumb: 'www.o2.co.uk/iPhone_16/O2',
        },
        {
          type: 'paid',
          rank_group: 2,
          rank_absolute: 13,
          domain: 'www.sky.com',
          title: 'AdiPhone 16 On Sky Mobile - No Mid-Contract Price Rises',
          description:
            "iPhone 16 From £26/m On Sky Mobile. The UK's Fastest Growing Network. You Can Roll Unused Data Each Month. Save It, Share It With Family & Exchange For Rewards.",
          url: 'https://www.sky.com/shop/mobile/phones/apple/apple-iphone-16',
          breadcrumb: 'www.sky.com/iPhone/16',
        },
        {
          type: 'organic',
          rank_group: 8,
          rank_absolute: 14,
          domain: 'www.apple.com',
          title: 'iPhone - Apple (IN)',
          description:
            'Online Personal Session Get to know your new iPhone. Whether you’re new to your Apple device or need a refresher on the latest features, schedule a free one‑on‑one session with a Specialist to set up your iPhone and get it ready to use.',
          url: 'https://www.apple.com/in/iphone/',
          breadcrumb: 'www.apple.com › in › iphone',
        },
        {
          type: 'organic',
          rank_group: 9,
          rank_absolute: 15,
          domain: 'www.apple.com',
          title: 'iPhone - Apple (PH)',
          description:
            'Make movies like the movies. iPhone records in HDR, so whether you use Action mode to steady really shaky scenes as you shoot or capture striking slo‑mo shots in 4K 120 fps Dolby Vision on iPhone 16 Pro — every frame looks incredible.',
          url: 'https://www.apple.com/ph/iphone/',
          breadcrumb: 'www.apple.com › ph › iphone',
        },
        {
          type: 'organic',
          rank_group: 10,
          rank_absolute: 16,
          domain: 'en.wikipedia.org',
          title: 'iPhone XS - Wikipedia',
          description:
            'The iPhone XS and iPhone XS Max (Roman numeral "X" pronounced as "ten" [16]) are smartphones designed, developed and marketed by Apple Inc. They are the twelfth-generation flagships of the iPhone, succeeding the iPhone X. [17]',
          url: 'https://en.wikipedia.org/wiki/IPhone_XS',
          breadcrumb: 'en.wikipedia.org › wiki › IPhone_XS',
        },
        {
          type: 'organic',
          rank_group: 11,
          rank_absolute: 17,
          domain: 'www.apple.com',
          title: 'iPhone - Apple (AE)',
          description:
            'Make movies like the movies. iPhone records in HDR, so whether you use Action mode to steady really shaky scenes as you shoot or capture striking slo‑mo shots in 4K 120 fps Dolby Vision on iPhone 16 Pro — every frame looks incredible.',
          url: 'https://www.apple.com/ae/iphone/',
          breadcrumb: 'www.apple.com › ae › iphone',
        },
        {
          type: 'organic',
          rank_group: 12,
          rank_absolute: 18,
          domain: 'www.apple.com',
          title: 'iPhone - Apple (IE)',
          description:
            'Make movies like the movies. iPhone records in HDR, so whether you use Action mode to steady really shaky scenes as you shoot or capture striking slo‑mo shots in 4K 120 fps Dolby Vision on iPhone 16 Pro — every frame looks incredible.',
          url: 'https://www.apple.com/ie/iphone/',
          breadcrumb: 'www.apple.com › ie › iphone',
        },
        {
          type: 'organic',
          rank_group: 13,
          rank_absolute: 19,
          domain: 'www.apple.com',
          title: 'iPhone - Compare Models - Apple (UK)',
          description:
            'Compare features and technical specifications for iPhone 16 Pro, iPhone 16 Pro Max, iPhone 16, iPhone 16 Plus, iPhone SE and many more.',
          url: 'https://www.apple.com/uk/iphone/compare/',
          breadcrumb: 'www.apple.com › uk › iphone',
        },
        {
          type: 'organic',
          rank_group: 14,
          rank_absolute: 20,
          domain: 'www.apple.com',
          title: 'iPhone - Buying iPhone - Apple (UK)',
          description:
            'Purchase your next iPhone from the Apple Store. Get answers about network providers, offers, payments, trade-in, setup and more.',
          url: 'https://www.apple.com/uk/iphone/buy/',
          breadcrumb: 'www.apple.com › uk › iphone',
        },
        {
          type: 'paid',
          rank_group: 3,
          rank_absolute: 21,
          domain: 'www.giffgaff.com',
          title: "AdUpgrade? Giffgaff's Got You - IPhone 14 Plus",
          description:
            "Level Up Your Photos When You Buy A Shiny New iPhone At giffgaff. Make Your iPhone Dreams Come True, Grab The Latest Phone With giffgaff's Perfect Plan",
          url: 'https://www.giffgaff.com/mobile-phones/apple/iphone-14-plus/new',
          breadcrumb: 'www.giffgaff.com',
        },
        {
          type: 'paid',
          rank_group: 4,
          rank_absolute: 22,
          domain: 'www.backmarket.co.uk',
          title: 'AdShop Refurbished iPhones - Up to 50% Less vs. Buying New',
          description:
            'Discover outstanding Apple iPhone deals! Up to 50% cheaper than new. Cheap Refurbished iPhone Deals | Back Market',
          url: 'https://www.backmarket.co.uk/en-gb/l/iphone/aabc736a-cb66-4ac0-a3b7-0f449781ed39',
          breadcrumb: 'www.backmarket.co.uk',
        },
        {
          type: 'paid',
          rank_group: 5,
          rank_absolute: 23,
          domain: 'www.carphonewarehouse.com',
          title: 'AdBuy The iPhone SE - Free Delivery 7 Days a Week',
          description:
            'We Offer Free Delivery 7 Days A Week, To Fit Right In With Your Busy Life. Order Now. We Compare Networks, Data and Duration So You Can Find The Deal That’s Right For You',
          url: 'https://www.carphonewarehouse.com/apple-iphone-se/',
          breadcrumb: 'www.carphonewarehouse.com/iPhone-SE',
        },
        {
          type: 'organic',
          rank_group: 15,
          rank_absolute: 25,
          domain: 'www.apple.com',
          title: 'Buy iPhone 15 and iPhone 15 Plus - Apple (UK)',
          description:
            'iPhone 15 or iPhone 15 Plus from only £29.12/mo. at 0% APR. Terms apply. Plus, trade in to lower your monthly payments.',
          url: 'https://www.apple.com/uk/shop/buy-iphone/iphone-15',
          breadcrumb: 'www.apple.com › uk › shop',
        },
        {
          type: 'organic',
          rank_group: 16,
          rank_absolute: 26,
          domain: 'www.apple.com',
          title: 'iPhone - Apple (ZA)',
          description:
            'Apple Footer. The display has rounded corners that follow a beautiful curved design, and these corners are within a standard rectangle. When measured as a standard rectangular shape, the screen is 5.42 inches ( iPhone 13 mini, iPhone 12 mini), 5.85 inches ( iPhone 11 Pro, iPhone XS, iPhone X), 6.06 inches ( iPhone 14, iPhone 13 Pro, iPhone 13, iPhone 12 Pro, iPhone 12, iPhone 11, iPhone XR), 6.12 ...',
          url: 'https://www.apple.com/za/iphone/',
          breadcrumb: 'www.apple.com › za › iphone',
        },
        {
          type: 'organic',
          rank_group: 17,
          rank_absolute: 27,
          domain: 'support.apple.com',
          title: 'iPhone XS - Technical Specifications – Apple Support (UK)',
          description:
            'Display. Super Retina HD display. 5.8‑inch (diagonal) all‑screen OLED Multi‑Touch display. HDR display. 2436‑by-1125‑pixel resolution at 458 ppi',
          url: 'https://support.apple.com/en-gb/111881',
          breadcrumb: 'support.apple.com › en-gb › 111881',
        },
        {
          type: 'organic',
          rank_group: 18,
          rank_absolute: 28,
          domain: 'www.techradar.com',
          title: 'iPhone XS review - TechRadar',
          description:
            "Jun 7, 2021 ·  Alongside the iPhone 11 range announcement, Apple confirmed that it would no longer sell the iPhone XS – it's being dropped from the company's line, but that doesn't mean you can't buy it.",
          url: 'https://www.techradar.com/reviews/iphone-xs-review',
          breadcrumb: 'www.techradar.com › reviews › iphone-xs',
        },
        {
          type: 'organic',
          rank_group: 19,
          rank_absolute: 29,
          domain: 'www.currys.co.uk',
          title:
            'APPLE iPhone SIM Free - Latest iPhone Models & Deals - Currys',
          description:
            'Land yourself a fantastic deal on APPLE products in the Mobile phones range here at Currys. Available online for delivery or order & collect.',
          url: 'https://www.currys.co.uk/phones/mobile-phones/mobile-phones/apple',
          breadcrumb: 'www.currys.co.uk › phones › mobile-phones',
        },
        {
          type: 'organic',
          rank_group: 20,
          rank_absolute: 30,
          domain: 'www.apple.com',
          title: 'iPhone Xs and iPhone Xs Max bring the best and biggest ...',
          description:
            'Sep 12, 2018 ·  “ iPhone Xs is packed with next-generation technologies and is a huge step forward for the future of the smartphone. Everything is state of the art including the industry-first 7-nanometer A12 Bionic chip with 8-core Neural Engine, faster Face ID and an advanced dual camera system that shoots Portrait mode photos with Smart HDR and dynamic depth of field,” said Philip Schiller, Apple ’s ...',
          url: 'https://www.apple.com/newsroom/2018/09/iphone-xs-and-iphone-xs-max-bring-the-best-and-biggest-displays-to-iphone/',
          breadcrumb: 'www.apple.com › newsroom › 2018',
        },
        {
          type: 'organic',
          rank_group: 21,
          rank_absolute: 31,
          domain: 'en.wikipedia.org',
          title: 'iPhone - Wikipedia',
          description:
            "The iPhone is a smartphone produced by Apple that uses Apple's own iOS mobile operating system.The first-generation iPhone was announced by then–Apple CEO Steve Jobs on January 9, 2007.",
          url: 'https://en.wikipedia.org/wiki/IPhone',
          breadcrumb: 'en.wikipedia.org › wiki › IPhone',
        },
        {
          type: 'organic',
          rank_group: 22,
          rank_absolute: 33,
          domain: 'www.apple.com',
          title: 'iPhone Xs and iPhone Xs Max bring the best and biggest ...',
          description:
            'Sep 12, 2018 ·  “ iPhone Xs is packed with next-generation technologies and is a huge step forward for the future of the smartphone. Everything is state of the art including the industry-first 7-nanometer A12 Bionic chip with 8-core Neural Engine, faster Face ID and an advanced dual camera system that shoots Portrait mode photos with Smart HDR and dynamic depth of field,” said Philip Schiller, Apple’s ...',
          url: 'https://www.apple.com/uk/newsroom/2018/09/iphone-xs-and-iphone-xs-max-bring-the-best-and-biggest-displays-to-iphone/',
          breadcrumb: 'www.apple.com › uk › newsroom',
        },
        {
          type: 'organic',
          rank_group: 23,
          rank_absolute: 34,
          domain: 'www.apple.com',
          title: 'iPhone SE - Apple (UK)',
          description:
            'Big-time battery life. A highly efficient chip, an enhanced battery and iOS 18 work together to boost battery life. When you do need to charge, just place iPhone SE on a wireless charger.',
          url: 'https://www.apple.com/uk/iphone-se/',
          breadcrumb: 'www.apple.com › uk › iphone-se',
        },
        {
          type: 'organic',
          rank_group: 24,
          rank_absolute: 35,
          domain: 'www.apple.com',
          title: 'iPhone - Apple (MY)',
          description:
            'Make movies like the movies. iPhone records in HDR, so whether you use Action mode to steady really shaky scenes as you shoot or capture striking slow‑motion shots in 4K 120 fps Dolby Vision on iPhone 16 Pro — every frame looks incredible.',
          url: 'https://www.apple.com/my/iphone/',
          breadcrumb: 'www.apple.com › my › iphone',
        },
        {
          type: 'organic',
          rank_group: 25,
          rank_absolute: 36,
          domain: 'www.apple.com',
          title: 'iPhone - Apple (HK)',
          description:
            'Make movies like the movies. iPhone records in HDR, so whether you use Action mode to steady really shaky scenes as you shoot or capture striking slo‑mo shots in 4K 120 fps Dolby Vision on iPhone 16 Pro — every frame looks incredible.',
          url: 'https://www.apple.com/hk/en/iphone/',
          breadcrumb: 'www.apple.com › hk › en',
        },
        {
          type: 'organic',
          rank_group: 26,
          rank_absolute: 37,
          domain: 'www.o2.co.uk',
          title: 'Best Apple iPhone Deals & Pay Monthly Contracts - O2',
          description:
            'Discover Apple iPhone. Shop the newest iPhones alongside our best pay monthly and pay as you go deals. Plus, enjoy exclusive O2 rewards. Available now with O2.',
          url: 'https://www.o2.co.uk/iphone',
          breadcrumb: 'www.o2.co.uk › iphone',
        },
        {
          type: 'organic',
          rank_group: 27,
          rank_absolute: 38,
          domain: 'www.apple.com',
          title: 'iPhone - Apple (SA)',
          description:
            'Make movies like the movies. iPhone records in HDR, so whether you use Action mode to steady really shaky scenes as you shoot or capture striking slo‑mo shots in 4K 120 fps Dolby Vision on iPhone 16 Pro — every frame looks incredible.',
          url: 'https://www.apple.com/sa/iphone/',
          breadcrumb: 'www.apple.com › sa › iphone',
        },
        {
          type: 'organic',
          rank_group: 28,
          rank_absolute: 39,
          domain: 'www.apple.com',
          title: 'iPhone - Apple (CA)',
          description:
            'Designed for Apple Intelligence. Discover the new iPhone 16 Pro, iPhone 16 Pro Max, iPhone 16, and iPhone 16 Plus.',
          url: 'https://www.apple.com/ca/iphone/',
          breadcrumb: 'www.apple.com › ca › iphone',
        },
        {
          type: 'organic',
          rank_group: 29,
          rank_absolute: 41,
          domain: 'm.gsmarena.com',
          title: 'Apple iPhone XS - Full phone specifications - GSMArena.com',
          description:
            'Apple iPhone XS smartphone. Announced Sep 2018. Features 5.8″ display, Apple A12 Bionic chipset, Dual: 12 MP (f/1.8, 26mm, 1/2.55″, 1.4µm) + 12 MP primary camera, 7 MP front camera, 2658 mAh battery, 512 GB storage, 4 GB RAM, Scratch-resistant glass.',
          url: 'https://m.gsmarena.com/apple_iphone_xs-9318.php',
          breadcrumb: 'm.gsmarena.com › apple_iphone_xs-9318',
        },
        {
          type: 'organic',
          rank_group: 30,
          rank_absolute: 42,
          domain: 'www.three.co.uk',
          title:
            'Apple iPhone Deals - Compare our Latest iPhone Contract Deals ...',
          description:
            '¹ Apple Intelligence will be available in beta on all iPhone 16 models, iPhone 15 Pro, and iPhone 15 Pro Max, with Siri and device language set to U.S. English, as an iOS 18 update in October 2024.',
          url: 'https://www.three.co.uk/mobile-phones/brands/apple-iphone',
          breadcrumb: 'www.three.co.uk › mobile-phones › brands',
        },
        {
          type: 'organic',
          rank_group: 31,
          rank_absolute: 43,
          domain: 'www.apple.com',
          title: 'iPhone - Apple (CZ)',
          description:
            'Natáčej videa jako z Hollywoodu. iPhone nahrává v HDR, takže ať při natáčení v akčním režimu stabilizuješ pořádně roztřesené záběry, nebo nahráváš iPhonem 16 Pro působivé zpomalené záběry ve 4K Dolby Vision při 120 fps, každé video vypadá fantasticky.',
          url: 'https://www.apple.com/cz/iphone/',
          breadcrumb: 'www.apple.com › cz › iphone',
        },
        {
          type: 'organic',
          rank_group: 32,
          rank_absolute: 44,
          domain: 'www.apple.com',
          title: 'Buy iPhone 14 and iPhone 14 Plus SIM Free - Apple (UK)',
          description:
            'iPhone 14 or iPhone 14 Plus from only £24.95/mo. at 0% APR. Terms apply. Plus, trade in to lower your monthly payments.',
          url: 'https://www.apple.com/uk/shop/buy-iphone/iphone-14',
          breadcrumb: 'www.apple.com › uk › shop',
        },
        {
          type: 'organic',
          rank_group: 33,
          rank_absolute: 45,
          domain: 'www.apple.com',
          title: 'iPhone - Compare Models - Apple',
          description:
            'Compare features and technical specifications for iPhone 16 Pro, iPhone 16 Pro Max, iPhone 16, iPhone 16 Plus, iPhone SE, and many more.',
          url: 'https://www.apple.com/iphone/compare/',
          breadcrumb: 'www.apple.com › iphone › compare',
        },
        {
          type: 'organic',
          rank_group: 34,
          rank_absolute: 46,
          domain: 'www.apple.com',
          title: 'iPhone - Apple (SG)',
          description:
            'Online Personal Session Get to know your new iPhone. Whether you’re new to your Apple device or need a refresher on the latest features, schedule a free one-on-one session with a Specialist to set up your iPhone and get it ready to use.',
          url: 'https://www.apple.com/sg/iphone/',
          breadcrumb: 'www.apple.com › sg › iphone',
        },
        {
          type: 'organic',
          rank_group: 35,
          rank_absolute: 47,
          domain: 'www.apple.com',
          title: 'Buy iPhone - Apple',
          description:
            'Shop the latest iPhone models and accessories. Save with Apple Trade In, carrier offers, and flexible monthly payment options. Get expert help today.',
          url: 'https://www.apple.com/shop/buy-iphone',
          breadcrumb: 'www.apple.com › shop › buy-iphone',
        },
        {
          type: 'organic',
          rank_group: 36,
          rank_absolute: 49,
          domain: 'www.which.co.uk',
          title: 'Best iPhone 2024: Which Apple iPhone Should I Buy? - Which?',
          description:
            'Aug 23, 2024 ·  Apple iPhones are typically very expensive, with no particularly budget-friendly options when you buy brand new. The iPhone 15 Pro Max is the highest-spec phone in the 15 series, launched in September 2023.',
          url: 'https://www.which.co.uk/reviews/mobile-phones/article/which-apple-iphone-should-i-buy-agShr2W5AgUA',
          breadcrumb: 'www.which.co.uk › reviews › mobile-phones',
        },
        {
          type: 'organic',
          rank_group: 37,
          rank_absolute: 50,
          domain: 'www.techradar.com',
          title: 'Best iPhone 2024: which Apple phone is for you? - TechRadar',
          description:
            "2 days ago ·  If you want the very best iPhone money can buy right now, the iPhone 16 Pro Max is the model to go for. The iPhone 15 Pro Max was already (and still is) an exceptional handset, but Apple's latest ...",
          url: 'https://www.techradar.com/news/best-iphone',
          breadcrumb: 'www.techradar.com › news › best-iphone',
        },
        {
          type: 'organic',
          rank_group: 38,
          rank_absolute: 51,
          domain: 'www.apple.com',
          title: 'iPhone - Apple (NZ)',
          description:
            'Designed for Apple Intelligence. Discover the new iPhone 16 Pro, iPhone 16 Pro Max, iPhone 16 and iPhone 16 Plus.',
          url: 'https://www.apple.com/nz/iphone/',
          breadcrumb: 'www.apple.com › nz › iphone',
        },
        {
          type: 'organic',
          rank_group: 39,
          rank_absolute: 52,
          domain: 'www.apple.com',
          title: 'Refurbished iPhone Deals - Apple (UK)',
          description:
            'Save up to 15% on a refurbished iPhone from Apple. Full 1-year warranty with a brand new battery and outer shell. Free delivery and returns.',
          url: 'https://www.apple.com/uk/shop/refurbished/iphone',
          breadcrumb: 'www.apple.com › uk › shop',
        },
        {
          type: 'organic',
          rank_group: 40,
          rank_absolute: 53,
          domain: 'www.amazon.co.uk',
          title: 'Amazon.co.uk: Iphone',
          description:
            'iPhone 16 Pro 128 GB: 5G Mobile phone with Camera Control, 4K 120 fps Dolby Vision and a Huge Leap in Battery Life. Works with AirPods; Desert Titanium',
          url: 'https://www.amazon.co.uk/iphone/s?k=iphone',
          breadcrumb: 'www.amazon.co.uk › iphone › s',
        },
        {
          type: 'organic',
          rank_group: 41,
          rank_absolute: 54,
          domain: 'www.apple.com',
          title: 'Apple Store Online - Apple (UK)',
          description:
            'The Apple Store Online offers the latest Apple products, accessories and flexible payment and delivery options.',
          url: 'https://www.apple.com/uk/store',
          breadcrumb: 'www.apple.com › uk › store',
        },
        {
          type: 'organic',
          rank_group: 42,
          rank_absolute: 55,
          domain: 'www.apple.com',
          title: 'iPhone - Apple（日本）',
          description:
            '生まれつきインテリジェント。 iPhone の最新モデルは、Apple Intelligenceのために設計されています。このパーソナルなインテリジェンスシステムは、あなたが文章を書いたり、自分を表現したり、タスクを簡単にこなせるようにサポート。',
          url: 'https://www.apple.com/jp/iphone/',
          breadcrumb: 'www.apple.com › jp › iphone',
        },
      ],
    },
  ],
} as any;
