import { ProjectEntity } from 'modules/projects/entities/project.entity';

export const newProjectForGoogleMaps = {
  projectName: 'starbucks',
  businessName: 'starbaks',
  url: null as string,
  id: 2,

  account: {
    id: 2,
  },
  keywords: [
    {
      name: 'starbucks loyalty rewards',
      positionUpdate: true,
      searchVolume: 0,
      cpc: 0,
      competitionIndex: 0,
      manualUpdateAvailable: true,
      id: 6,
    },
  ],
  language: {
    id: 37,

    code: 'en',
    name: 'English',
    serp: true,
    keywordData: true,
    serpBing: true,
    keywordDataBing: true,
    serpYouTube: true,
    serpYahoo: true,
    serpBaidu: false,
  },
  location: {
    id: 224,

    locationName: 'United Kingdom',
    locationCode: 2826,
    locationCodeParent: null as number,
    countryIsoCode: 'GB',
    locationType: 'Country',
    serp: true,
    keywordData: true,
    serpBing: true,
    keywordDataBing: false,
    serpYouTube: true,
    serpYahoo: true,
    serpBaidu: false,
  },
  searchEngine: { id: 3, name: 'Google Maps' },
  competitors: [] as any,
} as ProjectEntity;

export const newProjectForYoutube = {
  projectName: 'Burger',

  url: 'https://www.youtube.com/watch?v=xvoyUWXGivk',
  id: 64,

  account: {
    id: 7,
  },
  keywords: [
    {
      name: 'alec benjamin - can i sing for you?',
      positionUpdate: true,
      searchVolume: 0,
      cpc: 0,
      competitionIndex: 0,
      manualUpdateAvailable: true,
      id: 52,
    },
  ],
  language: {
    id: 37,
    code: 'en',
    name: 'English',
    serp: true,
    keywordData: true,
    serpBing: true,
    keywordDataBing: true,
    serpYouTube: true,
    serpYahoo: true,
    serpBaidu: false,
  },
  location: {
    id: 224,
    locationName: 'United Kingdom',
    locationCode: 2826,
    countryIsoCode: 'GB',
    locationType: 'Country',
    serp: true,
    keywordData: true,
    serpBing: true,
    keywordDataBing: true,
    serpYouTube: true,
    serpYahoo: false,
    serpBaidu: false,
  },
  searchEngine: { id: 7, name: 'YouTube' },
  urlType: null,
  competitors: [],
} as ProjectEntity;

export const newProjectForBing = {
  projectName: 'Bing',
  url: 'apple.com',
  id: 66,
  account: {
    id: 7,
  },
  keywords: [
    {
      name: 'iphone',
      positionUpdate: true,
      id: 54,
    },
  ],
  language: {
    id: 37,
    code: 'en',
    name: 'English',
    serp: true,
    keywordData: true,
    serpBing: true,
    keywordDataBing: true,
    serpYouTube: true,
    serpYahoo: true,
    serpBaidu: false,
  },
  location: {
    id: 224,
    locationName: 'United Kingdom',
    locationCode: 2826,
    countryIsoCode: 'GB',
    locationType: 'Country',
    serp: true,
    keywordData: true,
    serpBing: true,
    keywordDataBing: true,
    serpYouTube: true,
    serpYahoo: true,
    serpBaidu: false,
  },
  searchEngine: { id: 4, name: 'Bing' },
  urlType: { id: 2, name: 'url' },
  competitors: [],
} as ProjectEntity;

export const newProjectForYahoo = {
  projectName: 'Yahoo',
  url: 'www.metoffice.gov.uk',
  id: 65,
  account: {
    id: 7,
  },
  keywords: [
    {
      name: 'weather forecast',
      positionUpdate: true,
      manualUpdateAvailable: true,
      id: 53,
    },
  ],
  language: {
    id: 37,
    code: 'en',
    name: 'English',
    serp: true,
    keywordData: true,
    serpBing: true,
    keywordDataBing: true,
    serpYouTube: true,
    serpYahoo: true,
    serpBaidu: false,
  },

  location: {
    id: 224,
    locationName: 'United Kingdom',
    locationCode: 2826,

    countryIsoCode: 'GB',
    locationType: 'Country',
    serp: true,
    keywordData: true,
    serpBing: true,
    keywordDataBing: true,
    serpYouTube: true,
    serpYahoo: true,
    serpBaidu: false,
  },
  searchEngine: { id: 5, name: 'Yahoo' },
  urlType: { id: 2, name: 'url' },
  competitors: [],
} as ProjectEntity;
export const newProjectForGoogleLocal = {
  projectName: 'starbucks',
  businessName: 'starbaks',
  url: null as string,
  id: 2,

  account: {
    id: 2,
  },
  keywords: [
    {
      name: 'starbucks loyalty rewards',
      positionUpdate: true,
      searchVolume: 0,
      cpc: 0,
      competitionIndex: 0,
      manualUpdateAvailable: true,
      id: 6,
    },
  ],
  language: {
    id: 37,

    code: 'en',
    name: 'English',
    serp: true,
    keywordData: true,
    serpBing: true,
    keywordDataBing: true,
    serpYouTube: true,
    serpYahoo: true,
    serpBaidu: false,
  },
  location: {
    id: 224,

    locationName: 'United Kingdom',
    locationCode: 2826,
    locationCodeParent: null as number,
    countryIsoCode: 'GB',
    locationType: 'Country',
    serp: true,
    keywordData: true,
    serpBing: true,
    keywordDataBing: false,
    serpYouTube: true,
    serpYahoo: true,
    serpBaidu: false,
  },
  searchEngine: { id: 2, name: 'Google My Business' },
  competitors: [] as any,
} as ProjectEntity;

export const newProjectForGoogle = {
  projectName: 'Apple',
  businessName: null as string,
  url: 'apple.com',
  id: 1,

  account: {
    id: 1,
    companyName: null as string,
    companyUrl: null as string,
    tagline: null as string,
    twitterLink: null as string,
    facebookLink: null as string,
    linkedinLink: null as string,
    emailReports: true,
    sharedLinks: true,
    validatedBySerpnest: false,
    deletedAt: null as Date,
    apiKey: '',
  },
  keywords: [
    {
      name: 'iphone 3',
      positionUpdate: true,
      manualUpdateAvailable: true,
      id: 3,
    },
  ],
  language: {
    id: 37,
    code: 'en',
    name: 'English',
    serp: true,
    keywordData: true,
    serpBing: true,
    keywordDataBing: true,
    serpYouTube: true,
    serpYahoo: true,
    serpBaidu: false,
  },
  region: {
    id: 51,
    name: 'google.com',
    countryName: 'United States',
  },
  location: {
    id: 224,
    locationName: 'United Kingdom',
    locationCode: 2836,
    countryIsoCode: 'GB',
    locationType: 'Country',
    serp: true,
    keywordData: true,
    serpBing: true,
    keywordDataBing: false,
    serpYouTube: true,
    serpYahoo: true,
    serpBaidu: false,
  },
  searchEngine: { id: 1, name: 'Google' },
  urlType: { id: 1, name: 'domain' },
  competitors: [] as any,
} as ProjectEntity;
