export enum EventTypeEnum {
  'transaction.created' = 'transaction.created',
  'transaction.updated' = 'transaction.updated',
  'transaction.ready' = 'transaction.ready',
  'transaction.paid' = 'transaction.paid',
  'subscription.created' = 'subscription.created',
  'subscription.activated' = 'subscription.activated',
  'subscription.canceled' = 'subscription.canceled',
  'transaction.completed' = 'transaction.completed',
  'transaction.payment_failed' = 'transaction.payment_failed',
  'subscription.updated' = 'subscription.updated',
  'subscription.past_due' = 'subscription.past_due',
  'transaction.billed' = 'transaction.billed',
  'transaction.past_due' = 'transaction.past_due',
}
