export enum TariffPlansEnum {
  TrialPeriod = 'Trial Period',
  StarterPackage = 'Starter Package',
  StarterPlan = 'Starter Plan',
  ProfessionalPackage = 'Professional Package',
  ProfessionalPlan = 'Professional Plan',
  EnterprisePackage = 'Enterprise Package',
  EnterprisePlan = 'Enterprise Plan',
  Custom1Package = 'Custom 1 Package',
  Custom1Plan = 'Custom 1 Plan',
  Custom2Package = 'Custom 2 Package',
  Custom2Plan = 'Custom 2 Plan',
  Custom3Package = 'Custom 3 Package',
  Custom3Plan = 'Custom 3 Plan',
  Custom4Package = 'Custom 4 Package',
  Custom4Plan = 'Custom 4 Plan',
  Custom5Package = 'Custom 5 Package',
  Custom5Plan = 'Custom 5 Plan',
}
